packages:
  - 'packages/*'

allowBuilds:
  'esbuild': true
  'simple-git-hooks': false

catalog:
  '@eslint/compat': ^2.0.0
  '@stylistic/eslint-plugin': ^5.6.1
  '@tsconfig/node24': ^24.0.3
  '@types/ejs': ^3.1.5
  '@types/node': ^24.10.4
  '@types/prompts': ^2.4.9
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/tsconfig': ^0.8.1
  copyfiles: ^2.4.1
  ejs: ^3.1.10
  eslint: ^9.39.2
  eslint-plugin-vue: ~10.6.2
  jiti: ^2.6.1
  lint-staged: ^16.2.7
  npm-run-all2: ^8.0.4
  picocolors: ^1.1.1
  prompts: ^2.4.2
  publint: ^0.3.16
  rimraf: ^6.1.2
  simple-git-hooks: ^2.13.1
  tsdown: ^0.21.9
  typescript: ~5.9.3
  vitepress: ^1.6.4
  vue: ^3.5.26
  vue-tsc: ^3.2.1

cleanupUnusedCatalogs: true

dedupePeers: true

minimumReleaseAge: 1440
