# Publish package to the npm registry
name: Publish Package

on:
  # Run the workflow when a new tag is pushed starting with `v`
  # push:
  #  tags:
  #    - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm --dir packages/create-vue-lib run build
      - name: Publish
        run: pnpm --dir packages/create-vue-lib publish
